### ISSUE TITLE
Middleware example of reading request/response body 

### ISSUE THREAD

**Issue by desertjim** [terry90/rs-simple-proxy#3]
All of the examples I've seen for reading a hyper Body of the request or response are async. The methods in the middleware trait are not asynchronous. Is it possible to read the body contents in these methods?

If so can you provide an example of what this would look like?

**Comment by terry90** [comment]
Hi, this library does not use the new async/await syntax of Rust.
I would gladly accept a PR, but I won't do it myself anytime soon, sorry.

Edit: I bumped the dependencies to the last version of hyper
