### ISSUE TITLE
He doesn't support https?

### ISSUE THREAD

**Issue by zoain-it** [terry90/rs-simple-proxy#4]
Seems like my https is that requests are failing, only http is going through properly

**Comment by terry90** [comment]
I don't see why it would not work, could you provide an example ?

**Comment by zoain-it** [comment]
<img width="637" alt="截屏2020-06-18 下午4 45 07" src="https://user-images.githubusercontent.com/43292634/84998934-133fc580-b183-11ea-869e-0670c526fa39.png">
<img width="604" alt="截屏2020-06-18 下午4 45 40" src="https://user-images.githubusercontent.com/43292634/84999009-2783c280-b183-11ea-9c5d-3acb5e69f0fb.png">

This is the readme demo.

**Comment by terry90** [comment]
Oh I see, the goal of this project was not to enable https connection at first but if you are willing to add it I'll gladly accept a PR.
