### ISSUE TITLE
Unable to import Cors, Health, and Router middleware

### ISSUE THREAD

**Issue by jlarocque88** [terry90/rs-simple-proxy#5]
Hi, I'm new to Rust and trying to play with this proxy. I have installed various versions of simple-proxy with cargo, and they all fail to import the Cors, Health and Router middlewares, only Loggers works. Any idea why this might be?

```
unresolved imports `simple_proxy::middlewares::Cors`, `simple_proxy::middlewares::Health`, `simple_proxy::middlewares::Router`
no `Health` in `middlewares`
```

**Comment by terry90** [comment]
Hi, as you can see here: [src/middlewares/mod.rs](https://github.com/terry90/rs-simple-proxy/blob/master/src/middlewares/mod.rs) you have to set the correct features in your `Cargo.toml` when importing the crate: `["health", "cors", "router"]`
